services:
  - type: web
    name: pypsa-implementation
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
